// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGd0LHBZsbr9YOYzQll_fj8mIlQXb3HhA',
    appId: '1:247425422872:web:76382fb0919d9f64f2156d',
    messagingSenderId: '247425422872',
    projectId: 'bhromon-6e9c5',
    authDomain: 'bhromon-6e9c5.firebaseapp.com',
    storageBucket: 'bhromon-6e9c5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCojJm7F5hhS3GLF1gAiMl4Pc8e_WJ-CIw',
    appId: '1:247425422872:android:c37dde6af83bb6ecf2156d',
    messagingSenderId: '247425422872',
    projectId: 'bhromon-6e9c5',
    storageBucket: 'bhromon-6e9c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvi6wNKbFmg04ZiPBAihksJcr36Vhz2Do',
    appId: '1:247425422872:ios:4d17746fe9479e78f2156d',
    messagingSenderId: '247425422872',
    projectId: 'bhromon-6e9c5',
    storageBucket: 'bhromon-6e9c5.appspot.com',
    iosBundleId: 'com.example.bhromon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvi6wNKbFmg04ZiPBAihksJcr36Vhz2Do',
    appId: '1:247425422872:ios:70ed2ba3ecd1f256f2156d',
    messagingSenderId: '247425422872',
    projectId: 'bhromon-6e9c5',
    storageBucket: 'bhromon-6e9c5.appspot.com',
    iosBundleId: 'com.example.bhromon.RunnerTests',
  );
}
